### Bulk documents

### Get all customer
GET http://localhost:9200/customers/_search

### Bulk api
POST http://localhost:9200/_bulk
Content-Type: application/json

< bulk.json

### Get document joko
GET http://localhost:9200/customers/_doc/joko

### Get document budi
GET http://localhost:9200/customers/_doc/budi

### Get document spammer
GET http://localhost:9200/customers/_doc/spammer
