### update customers_v2 mapping
PUT http://localhost:9200/customers_v2/_mapping
Content-Type: application/json

{
  "properties" : {
    "address" : {
      "properties" : {
        "street" : {
          "type" : "text"
        },
        "city" : {
          "type" : "text"
        },
        "province" : {
          "type" : "text"
        },
        "country" : {
          "type" : "text"
        },
        "zip_code" : {
          "type" : "keyword"
        }
      }
    }
  }
}

### get mapping customers_v2
GET http://localhost:9200/customers_v2/_mapping

### insert customers
POST http://localhost:9200/_bulk
Content-Type: application/json

< customers-with-addresses.json

### search customer
GET http://localhost:9200/customer/_search