### Update products mapping
PUT http://localhost:9200/products/_mapping
Content-Type: application/json

{
    "date_detection" : true,
    "dynamic_date_formats" : [
        "yyyy-MM-dd HH:mm:ss",
        "yyyy-MM-dd",
        "yyyy/MM/dd HH:mm:ss",
        "yyyy/MM/dd"
    ]
}

### Get Mapping
GET http://localhost:9200/products/_mapping


### Update products mapping
PUT http://localhost:9200/products/_mapping
Content-Type: application/json

{
    "numeric_detection": true
}

### Get Mapping
GET http://localhost:9200/products/_mapping


### Create products 1
POST http://localhost:9200/products/_create/1
Content-Type: application/json

{
    "name": "Indomie Ayam Bawang",
    "price": "2000"
}

### Create products 2
POST http://localhost:9200/products/_create/2
Content-Type: application/json

{
    "name": "Mie Sedap Soto",
    "price": "2000"
}

### Get Mapping
GET http://localhost:9200/products/_mapping


# MULTI GET API
### Multiget products
POST http://localhost:9200/products/_mget
Content-Type: application/json

{
    "ids": [
        "1",
        "2"
    ]
}

# SEARCH API
### Serach all products
POST http://localhost:9200/products/_search

# PAGINATION
### Serach products page 1
POST http://localhost:9200/products/_search?size=1&from=0

### Serach products page 2
POST http://localhost:9200/products/_search?size=1&from=1

# SORTING
### Search products sort by price asc
POST http://localhost:9200/products/_search?sort=price:asc

### Search products sort by name asc (failed)
POST http://localhost:9200/products/_search?sort=name:asc


# INDEXING (REPLACE)
### Save product 3
POST http://localhost:9200/products/_doc/3
Content-Type: application/json

{
    "name": "Pop Mie Rasa Bakso",
    "price": 2500
}

### Save product 4
POST http://localhost:9200/products/_doc/4
Content-Type: application/json

{
    "name": "Samsung Galaxy A14",
    "price": 2499000
}
### Save product 5
POST http://localhost:9200/products/_doc/5
Content-Type: application/json

{
    "name": "Asus Vivobook 14X",
    "price": 7862000
}

### Search all products
POST http://localhost:9200/products/_search



# UPDATE DOCUMENT PER ATTRIBUTE
### Update product 1
POST http://localhost:9200/products/_update/1
Content-Type: application/json

{
    "doc": {
        "price": 3000
    }
}

### Search all products
POST http://localhost:9200/products/_search