### search to products
GET http://localhost:9200/products/_search

### search to order
GET http://localhost:9200/order/_search

### select total, customer_id, items.product_d from order
GET http://localhost:9200/order/_search?_source_includes=total,customer_id,items.product_id

### select *, exclude price from products
GET http://localhost:9200/products/_search?_source_excludes=price

### select total, customer_id from order where _id = 1
GET http://localhost:9200/order/_doc/1?_source_includes=total,customer_id