### search customer where gender = 'Female'
POST http://localhost:9200/customer/_search
Content-Type: application/json

{
  "query" : {
    "term" : {
      "gender" : "Female"
    }
  },
  "size" : 5,
  "from" : 0,
  "sort" : [
    {
      "username" : {
        "order": "desc"
      }
    }
  ]
}

### search customer where banks.name = 'BCA'
POST http://localhost:9200/customer/_search
Content-Type: application/json

{
  "query" : {
    "term" : {
      "banks.name" : "BCA"
    }
  },
  "size" : 5,
  "from" : 0,
  "sort" : [
    {
      "username" : {
        "order": "desc"
      }
    }
  ]
}
